name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Prevent multiple runs of the same workflow on a PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ESLint & Prettier
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        id: format
        run: pnpm format:check
        continue-on-error: true

      - name: Run ESLint
        id: lint
        run: pnpm lint
        continue-on-error: true

      - name: Report status
        if: always()
        run: |
          if [ "${{ steps.format.outcome }}" == "failure" ] || [ "${{ steps.lint.outcome }}" == "failure" ]; then
            echo "::error::Code quality checks failed!"
            echo "::error::Formatting check status: ${{ steps.format.outcome }}"
            echo "::error::Lint check status: ${{ steps.lint.outcome }}"
            echo "Run 'pnpm format' and 'pnpm lint:fix' locally to fix issues."
            exit 1
          fi
